services:
  - type: web
    name: churn-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.core.main:app --host 0.0.0.0 --port 10000
    plan: free
